import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";


const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})


export const metadata = {
  title: "Home - Dhruva Astronmy Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[url('/Images/background.png')]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
